repos:
  - hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: go-fmt
      - id: go-imports # sudo apt install golang-golang-x-tools
      - id: no-go-testing
      - id: golangci-lint # sudo snap install golangci-lint --classic
        entry: bash -c "cd npu-device-plugin && golangci-lint run ./..."
        language: system
    repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
  - hooks:
      - args:
          - --config
          - .github/linters/.markdown-lint.yml
        id: markdownlint
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
  - hooks:
      - id: shellcheck
    repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
  - hooks:
      - id: actionlint
    repo: https://github.com/rhysd/actionlint
    rev: v1.7.5
  - hooks:
      - id: shfmt
    repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
  - hooks:
      - id: black
    repo: https://github.com/ambv/black
    rev: 24.10.0

  - hooks:
      - args:
          - --profile=black
        id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.13.2
  - hooks:
      - id: helm-docs
    repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
