apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencode-v2.fullname" . }}-config
  labels:
    {{- include "opencode-v2.labels" . | nindent 4 }}
data:
  opencode.json: |
    {{- .Values.opencodeConfig | nindent 4 }}
