apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DB_ENGINE
          value: postgres
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.global.postgresql.postgresqlPassword | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.global.postgresql.postgresqlDatabase | quote }}
        - name: POSTGRES_SERVER
          value: "{{ .Release.Name}}-postgresql-headless"
        - name: POSTGRES_PORT
          value: {{ .Values.postgresql.global.postgresql.servicePort | quote }}
        volumeMounts:
        - name: mealie-data
          mountPath: /app/data
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc