apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        #How to see if you need to spin one up or not. Basically break down if, else statments.
      - name: postgres
        image: postgres
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_PASSWORD
          value: mealie
        - name: POSTGRES_USER
          value: mealie
        - name: POSTGRES_DB
          value: mealie
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
        