apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mealie.replicas }}
  selector:
    matchLabels:
      {{- include "mealie.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mealie.selectorLabels" . | nindent 8 }}
        {{- with .Values.customLabels.mealie }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mealie.fullname" . }}-data
      containers:
        - name: mealie
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BASE_URL
            value: "{{ if .Values.ingress.enabled }}https://{{ (index .Values.ingress.hosts 0).host }}{{ else }}http://localhost:8080{{ end }}"
          {{- with .Values.mealie.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
          - name: data
            mountPath: /app/data
          ports:
          - name: http
            containerPort: {{ .Values.mealie.service.port }}
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.mealie.initialDelaySeconds }}
            httpGet:
              path: /api/app/about
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.mealie.initialDelaySeconds }}
            httpGet:
              path: /api/app/about
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- with .Values.customLabels.postgres }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.customLabels.postgres }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.postgresRepo }}:{{ .Values.image.pgtag }}"
          ports:
            - containerPort: {{ .Values.postgres.service.port}}
          env:
          {{- with .Values.postgres.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: {{ .Values.postgres.initialDelaySeconds }}
            timeoutSeconds: 20
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: {{ .Values.postgres.initialDelaySeconds }}
            timeoutSeconds: 20
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ include "mealie.fullname" . }}-pgdata
{{- end }}
