apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "750m"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: mealie-data
          mountPath: /app/data
        ports:
          - name: app
            containerPort: {{ .Values.port }}
            protocol: TCP
        env:
          - name: BASE_URL
            value: http://mealie.tail79a5c8.ts.net/
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc