apiVersion: v1
kind: Service
metadata:
  name: mealie-server
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    tailscale.com/proxy-class: control-plane
  name: mealie
  namespace: mealie
spec:
  ingressClassName: tailscale
  rules:
  - host: mealie
    http:
      paths:
      - backend:
          service:
            name: mealie-server
            port:
              name: app
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mealie