apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-ingress
spec:
  defaultBackend:
    service:
      name: mealie-service
      port:
        number: {{ .Values.service.port }}
  ingressClassName: tailscale
  tls:
    - hosts:
        - mealie # The hostname you want to access the service by