apiVersion: v1
kind: Service
metadata:
  name: mealie-server
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: app
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}