apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    tailscale.com/proxy-class: control-plane
  name: mealie
  namespace: mealie
spec:
  ingressClassName: tailscale
  rules:
  - host: mealie
    http:
      paths:
      - backend:
          service:
            name: mealie-server
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mealie