apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
spec:
  defaultBackend:
    service:
      name: mealie
      port:
        number: {{ .Values.service.port }}
  ingressClassName: tailscale
  tls:
    - hosts:
        - mealie # The hostname you want to access the service by