apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mealie.service.type }}
  ports:
    - port: {{ .Values.mealie.service.port }}
      targetPort: http
      protocol: TCP
      name:
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
    {{- with .Values.customLabels.mealie }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-mealie
spec:
  type: {{ .Values.postgres.service.type}}
  ports:
    - port:  {{ .Values.postgres.service.port}}
      targetPort:  {{ .Values.postgres.service.port}}
  selector:
    {{- with .Values.customLabels.postgres }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
