apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
