apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-engine.fullname" . }}-data
  labels:
    {{- include "agent-engine.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.checkpoint.storage }}
