apiVersion: v2
name: kavita
description: Self-hosted digital library for comics, manga, and ebooks
type: application
version: 1.0.0
appVersion: 0.8.4
dependencies:
  - name: app-template
    version: 3.5.1
    repository: https://bjw-s-labs.github.io/helm-charts/
