{
 "title": "NVIDIA Jetson",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_uptime{node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Board Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "jetson_info_board_info{node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Board Hardware Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "jetson_info_hardware_info{node=~\"$Node\"}"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_usage_cpu{node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_usage_ram{memory=\"used\", node=~\"$Node\"}",
     "legendFormat": "{{memory}}"
    },
    {
     "expr": "jetson_usage_ram{memory=\"tot\", node=~\"$Node\"}",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_usage_gpu{node=~\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_usage_fan{fan=\"speed\", node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_usage_disk{disk=\"used\", node=~\"$Node\"}",
     "legendFormat": "{{disk}}"
    },
    {
     "expr": "jetson_usage_disk{disk=\"total\", node=~\"$Node\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Power and Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_usage_power{node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Sensor Temperatures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetson_temperatures{node=~\"$Node\"}"
    }
   ]
  }
 ]
}