# https://github.com/longhorn/longhorn/tree/master/chart
defaultSettings:
  defaultDataPath: /storage
ingress:
  enabled: true
  host: longhorn
  ingressClassName: tailscale
  tls: true
  tlsSecret:
metrics:
  serviceMonitor:
    annotations:
      prometheus: monitoring-kube-prometheus-prometheus
      release: monitoring
    enabled: true
service:
  ui:
    loadBalancerIP: 192.168.1.81
    type: LoadBalancer
