apiVersion: v2
name: qbittorrent
description: BitTorrent client with web interface for downloading media
type: application
version: 1.0.0
appVersion: 4.6.2
dependencies:
  - name: app-template
    version: 3.5.1
    repository: https://bjw-s-labs.github.io/helm-charts/