apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-mcp-rbac
  namespace: argocd
  labels:
    stack: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tylertitsworth/ai-cluster.git
    targetRevision: main
    path: charts/kubernetes-mcp-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-mcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
