apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "langgraph-serve.fullname" . }}-data
  labels:
    {{- include "langgraph-serve.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.checkpoint.storage }}
