apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr-data
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
