# Longhorn
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    stack: system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.1
    helm:
      values: |
        defaultSettings:
          defaultDataPath: /storage
        metrics:
          serviceMonitor:
            additionalLabels:
              prometheus: monitoring-kube-prometheus-prometheus
              release: monitoring
            enabled: true
        ingress:
          enabled: true
          host: longhorn
          ingressClassName: tailscale
          tls: true
          tlsSecret:
        service:
          ui:
            loadBalancerIP: 192.168.0.81
            nodePort: 31835
            type: LoadBalancer
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
