# Open WebUI - Web Interface for LLMs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-webui.github.io/helm-charts
      chart: open-webui
      targetRevision: 10.2.1
      helm:
        parameters:
          - forceString: true
            name: image.repository
            value: ghcr.io/open-webui/open-webui
          - forceString: true
            name: image.tag
            value: v0.8.10
        valueFiles:
          - $values/manifests/argocd/open-webui-values.yaml
    - repoURL: https://github.com/tylertitsworth/ai-cluster.git
      targetRevision: servarr-stack
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
