# Open WebUI - Web Interface for LLMs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-webui.github.io/helm-charts
      chart: open-webui
      targetRevision: 12.10.0
      helm:
        parameters:
          - forceString: true
            name: image.repository
            value: ghcr.io/open-webui/open-webui
          - forceString: true
            name: image.tag
            value: latest
          - forceString: true
            name: fullnameOverride
            value: open-webui
          - forceString: true
            name: ollama.fullnameOverride
            value: open-webui-ollama
          - forceString: true
            name: pipelines.fullnameOverride
            value: open-webui-pipelines
          - forceString: true
            name: websocket.url
            value: redis://open-webui-redis:6379/0
        valueFiles:
          - $values/apps/values/open-webui-values.yaml
    - repoURL: https://github.com/tylertitsworth/ai-cluster.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
