apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restart-operator-crds
  namespace: argocd
  labels:
    stack: servarr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tylertitsworth/ai-cluster.git
    targetRevision: restart-operator
    path: charts/restart-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: servarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
