# Synology CSI Driver
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  labels:
    stack: storage
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: synology-csi
  sources:
    - repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
      chart: synology-csi
      targetRevision: 0.11.2
      helm:
        valueFiles:
          - $values/apps/values/synology-csi-values.yaml
    - repoURL: https://github.com/tylertitsworth/ai-cluster.git
      targetRevision: synology-csi
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
