app-template:
  controllers:
    terraria:
      replicas: 1
      strategy: Recreate

      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

      containers:
        main:
          image:
            repository: totalsundae/dev
            tag: terraria
            pullPolicy: Always

          env:
            TZ: America/Los_Angeles

  service:
    main:
      controller: terraria
      type: ClusterIP
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "terraria"
        tailscale.com/proxy-class: "pin-framework-desktop"
      ports:
        game:
          port: 7777
          protocol: TCP

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
      globalMounts:
        - path: /home/terraria/.local/share/Terraria

    serverconfig:
      enabled: true
      type: configMap
      name: terraria-serverconfig
      globalMounts:
        - path: /home/terraria/.local/share/Terraria/serverconfig.txt
          subPath: serverconfig.txt

serverConfig: |
  world=/home/terraria/.local/share/Terraria/Worlds/coop-tyler-nathan-kaitlynd.wld
  worldname=coop-tyler-nathan-kaitlynd
  maxplayers=8
  port=7777
  password=password
  motd=Welcome to the Terraria server!
  priority=1
  npcstream=1
  secure=1
  language=en-US
