app-template:
  controllers:
    komf:
      replicas: 1
      strategy: Recreate

      containers:
        main:
          image:
            repository: sndxr/komf
            tag: latest
            pullPolicy: IfNotPresent

          env:
            TZ: America/Los_Angeles

          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8085
                initialDelaySeconds: 60
                periodSeconds: 30
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8085
                initialDelaySeconds: 30
                periodSeconds: 10

          resources:
            requests:
              memory: 256Mi
              cpu: 50m
            limits:
              memory: 1Gi

  service:
    main:
      controller: komf
      ports:
        http:
          port: 8085

  ingress:
    main:
      enabled: true
      className: tailscale
      hosts:
        - host: komf
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      annotations:
        tailscale.com/proxy-class: "control-plane"
      tls:
        - hosts:
            - komf

  configMaps:
    config:
      data:
        application.yml: |
          komf:
            kavita:
              baseUri: "http://kavita.servarr.svc.cluster.local:5000"
              apiKey: "34d9d9b7-f198-4197-840f-c968a1ae0c6b"
              eventListener:
                enabled: false # if disabled will not connect to kavita and won't pick up newly added entries
                metadataLibraryFilter: [ ]  # listen to all events if empty
                metadataSeriesExcludeFilter: [ ]
                notificationsLibraryFilter: [ ] # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
              metadataUpdate:
                default:
                  libraryType: "MANGA" # Can be "MANGA", "NOVEL", "COMIC" or "WEBTOON". Hint to help better match book numbers
                  updateModes: [ API ] # can use multiple options at once. available options are API, COMIC_INFO
                  aggregate: false # if enabled will search and aggregate metadata from all configured providers
                  mergeTags: false # if true and aggregate is enabled will merge tags from all providers
                  mergeGenres: false # if true and aggregate is enabled will merge genres from all providers
                  bookCovers: false #update book thumbnails
                  seriesCovers: false #update series thumbnails
                  overrideExistingCovers: true # if false will upload but not select new cover if another cover already exists
                  lockCovers: true # lock cover images so that kavita does not change them
                  postProcessing:
                    seriesTitle: false #update series title
                    seriesTitleLanguage: "en" # series title update language. If empty chose first matching title
                    alternativeSeriesTitles: false # use other title types as alternative title option
                    alternativeSeriesTitleLanguages: # alternative title language. Only first language is used. Use single value for consistency
                      - "ja-ro"
                    orderBooks: false # will order books using parsed volume or chapter number. works only with COMIC_INFO
                    languageValue: # set default language for series. Must use BCP 47 format e.g. "en"
            
            database:
              file: /data/database.sqlite
            
            metadataProviders:
              malClientId: "" # required for mal provider. See https://myanimelist.net/forum/?topicid=1973077 env:KOMF_METADATA_PROVIDERS_MAL_CLIENT_ID
              comicVineApiKey: # required for comicVine provider https://comicvine.gamespot.com/api/ env:KOMF_METADATA_PROVIDERS_COMIC_VINE_API_KEY
              comicVineSearchLimit: # define ComicVine search result Limit, default is 10
              comicVineIssueName: # string that contains "{number}" which will be replaced by the issue number ie. "Issue #{number}". Used when an issue has no name on ComicVine, default is null
              comicVineIdFormat: # string that contains "{id}" which will serve to parse the ComicVine volume of a given book from its title or folder name ie. "[cv-{id}]" which will correctly identify '.../Uncanny X-Men Omnibus (2006) [cv-27512]' as being [4050-27512](https://comicvine.gamespot.com/uncanny-x-men-omnibus/4050-27512/)
              bangumiToken: # bangumi provider require a token to show nsfw items https://next.bgm.tv/demo/access-token  env:KOMF_METADATA_PROVIDERS_BANGUMI_TOKEN
              defaultProviders:
                mangaUpdates:
                  priority: 10
                  enabled: true
                  mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON. MANGA type includes everything except novels
                  authorRoles: [ "WRITER" ] # roles that will be mapped to author role
                  artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ] # roles that will be mapped to artist role
                mal:
                  priority: 20
                  enabled: false
                  mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON. MANGA type includes everything except novels
                nautiljon:
                  priority: 30
                  enabled: false
                aniList:
                  priority: 40
                  enabled: false
                  mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON. MANGA type includes everything except novels
                  tagsScoreThreshold: 60 # tags with this score or higher will be included
                  tagsSizeLimit: 15 # amount of tags that will be included
                yenPress:
                  priority: 50
                  enabled: false
                  mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
                kodansha:
                  priority: 60
                  enabled: false
                viz:
                  priority: 70
                  enabled: false
                bookWalker:
                  priority: 80
                  enabled: false
                  mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON.
                mangaDex:
                  priority: 90
                  enabled: false
                  coverLanguages:
                    - "en"
                    - "ja"
                bangumi: # Chinese metadata provider. https://bgm.tv/
                  priority: 100
                  enabled: false
                comicVine: # https://comicvine.gamespot.com/ requires API key. Experimental provider, can mismatch issue numbers
                  priority: 110
                  enabled: false
                hentag:
                  priority: 120
                  enabled: false
                webtoons:
                  priority: 130
                  enabled: false
                mangaBaka:
                  priority: 140
                  enabled: false
                  # Datasource used for metadata retrieval. DATABASE mode will only work if MangaBaka database is installed
                  # API or DATABASE 
                  mode: API

            server:
              port: 8085 # or env:KOMF_SERVER_PORT

            logLevel: INFO # or env:KOMF_LOG_LEVEL

  persistence:
    config:
      enabled: true
      type: configMap
      name: komf-config
      globalMounts:
        - path: /config/application.yml
          subPath: application.yml
          readOnly: true

    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
