name: build-jetson-exporter-container
on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - 'jetson-exporter/Dockerfile'
      - 'jetson-exporter/exporter.py'
      - 'jetson-exporter/requirements.txt'
  pull_request:
    paths:
      - 'jetson-exporter/Dockerfile'
      - 'jetson-exporter/exporter.py'
      - 'jetson-exporter/requirements.txt'

jobs:
  build:
    uses: ./.github/workflows/build-container.yaml
    with:
      image: jetson-exporter
      context: jetson-exporter
      dockerfile: ./jetson-exporter/Dockerfile
