name: build-npu-device-plugin-container
permissions:
  contents: read
  packages: write
on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - 'npu-device-plugin/*.go'
      - 'npu-device-plugin/Dockerfile'
      - 'npu-device-plugin/go.*'
  pull_request:
    paths:
      - 'npu-device-plugin/*.go'
      - 'npu-device-plugin/Dockerfile'
      - 'npu-device-plugin/go.*'

jobs:
  build:
    uses: ./.github/workflows/build-container.yaml
    with:
      image: npu-device-plugin
      context: .
      dockerfile: ./npu-device-plugin/Dockerfile
