name: build-npu-device-plugin-container
on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - 'npu-device-plugin/*.go'
      - 'npu-device-plugin/Dockerfile'
      - 'npu-device-plugin/go.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/npu-device-plugin
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./npu-device-plugin/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
  deploy:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v4
      - uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions
      - run: sleep 15
      - uses: azure/setup-kubectl@v4
      - name: Deploy Daemonset
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl rollout restart -n kube-system daemonset/npu-device-plugin
